/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Button: typeof import('./src/components/kits/Button.vue')['default']
    CustomCursor: typeof import('./src/components/kits/CustomCursor.vue')['default']
    DetailItem: typeof import('./src/components/DetailItem.vue')['default']
    Intro: typeof import('./src/components/Intro.vue')['default']
    Nav: typeof import('./src/components/Nav.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    Pen: typeof import('./src/components/kits/Pen/index.vue')['default']
    Poem: typeof import('./src/components/Poem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Title: typeof import('./src/components/Title.vue')['default']
  }
}
